services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.back
    ports:
      - 3000:3000
    environment:
      - HTTP_PORT=3000
      - MONGO_URL=mongodb://mongo:27017/my-mongo
      - JWT_SECRET=secret
      - JWT_EXPIRES=365d
    networks:
      - app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.front
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    environment:
      - VITE_MAIN_URL=http://backend:3000/api
      - VITE_SERVER_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  mongo_data:

